name: Github Output Test

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  rebase-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: sh test
        run: sh .github/workflows/bin/test.sh
