name: Github Output Test1

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  rebase-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: sh test
        run: /bin/bash .github/workflows/bin/test1.sh
