name: hoge

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  hoge-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Slack notification for ridgepole apply log
        run: /bin/bash .github/workflows/bin/test10.sh
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
